# 第四章 数组与向量化计算

Numpy,是Numerical Pyethon的简称

## 4.1 Numpy ndarray: 多维数组对象

In [2]:
# 标准导入方式,numpy名字空间包含了大量与Python内建函数重名的函数（比如min和max）
import numpy as np 

一个 `ndarray` 是一个通用的多维同类数据容器，也就是说它包含的每一个元素均为相同类型   
每一个数组有一个 `shape` 属性，用来表征数组每一个维度的数量    
每一个数组有一个 `dtype` 属性用来描述数组的数据类型

In [7]:
data = np.random.randn(2, 3)

In [8]:
data

array([[ 0.22123902, -0.18409613,  0.60669371],
       [ 0.45175631,  0.74623903,  0.75281316]])

In [9]:
data * 10

array([[ 2.21239023, -1.84096127,  6.06693707],
       [ 4.51756313,  7.46239032,  7.52813162]])

In [10]:
data + data

array([[ 0.44247805, -0.36819225,  1.21338741],
       [ 0.90351263,  1.49247806,  1.50562632]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

### 4.1.1 生成ndarray


array函数接收任意的序列型对象（当然也包括其他数组），生成的新的包含数据的numpy数组
除非显式指定，否则np.array会自动推断生成数组的数据类型       
`zeros`  生成全0数组   
`ones`  生成全1数组    
`empty`  创建一个没有初始化的数组   
`arange`  Python内建函数range的数组版     

In [15]:
a = np.arange(15)

可以使用astype显式转换数据类型,总是生成一个新的数组

In [20]:
a.astype('string_')

array([b'0', b'1', b'2', b'3', b'4', b'5', b'6', b'7', b'8', b'9', b'10',
       b'11', b'12', b'13', b'14'], dtype='|S11')

In [18]:
a.astype('int32')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Numpy数组算数

In [22]:
a.astype('float')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14.])

In [23]:
a * a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [24]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
1 / (a + 1)

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
       0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667])

In [27]:
a ** 0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [29]:
a > a**0.5

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

如果想要一份数组切片的拷贝而不是一份视图的话，就必须显式地复制这个数组

In [31]:
a[8:9].copy()

array([8])

In [32]:
arr2d =[[1,2,3],[4,5,6],[7,8,9]]

In [33]:
arr2d[0][1]

2

## 数组转置和转轴

In [47]:
arr = np.arange(15).reshape(3, 5)

In [43]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [45]:
np.transpose(arr)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

计算内积用np.dot

In [46]:
a = np.random.randn(6, 3)
np.dot(a, arr)

array([[-10.8775722 , -11.13078885, -11.3840055 , -11.63722215,
        -11.8904388 ],
       [  8.9103772 ,   9.54230082,  10.17422443,  10.80614805,
         11.43807166],
       [-18.08839188, -20.22019317, -22.35199446, -24.48379576,
        -26.61559705],
       [  2.66420278,   2.97298874,   3.2817747 ,   3.59056065,
          3.89934661],
       [ -9.51188576,  -9.28186023,  -9.0518347 ,  -8.82180916,
         -8.59178363],
       [ -2.96330978,  -3.70988213,  -4.45645447,  -5.20302682,
         -5.94959917]])

对于更高维度的数组，transpose可以接收包含轴编号的元组，用于置换轴

In [52]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

## 通用函数：快速的逐元素数组函数

In [54]:
np.sqrt(arr)

array([[[0.        , 1.        , 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974, 2.64575131]],

       [[2.82842712, 3.        , 3.16227766, 3.31662479],
        [3.46410162, 3.60555128, 3.74165739, 3.87298335]]])

In [57]:
np.subtract(arr, np.sqrt(arr))

array([[[ 0.        ,  0.        ,  0.58578644,  1.26794919],
        [ 2.        ,  2.76393202,  3.55051026,  4.35424869]],

       [[ 5.17157288,  6.        ,  6.83772234,  7.68337521],
        [ 8.53589838,  9.39444872, 10.25834261, 11.12701665]]])

In [12]:
y = np.ones(3)

In [25]:
np.shape(y)

(3,)

In [15]:
x = np.array([[1, 2, 3],[4, 5, 6]])

In [26]:
np.shape(x)

(2, 3)

In [22]:
z = np.dot(y.T, x)

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)

In [23]:
z

array([ 6., 15.])